export { default as Navbar } from './Navbar/Navbar';
export { default as NavigationDots } from './NavigationDots';
export { default as SocialMedia } from './SocialMedia';
export { default as Projects } from './Projects/Projects';
export { default as Chatbot } from './Chatbot/Chatbot';
export { default as Contact} from './ContactPage/ContactPage';
export { default as LanguageSwitcher } from './LanguageSwitcher/LanguageSwitcher';
export { default as Assistants } from './Assistants/Assistants';
export { default as Building } from './Building/Building';
export { default as Web } from './Web/Web';
export { default as Video } from './Video/Video';
export { default as Resources } from './Resources/Resources';
export { default as Design } from './Design/Design';
